### ISSUE TITLE
[PROPOSAL] combining input datasets in case of partitions

### ISSUE THREAD

**Issue by rahul-madaan** [OpenLineage/OpenLineage#3306]
**Problem:**
1. end user gets `n` input dataset if the dataset is divided into partitions
3. This creates a disconnect between logical and physical representation:
   - Logically: User operates on a single dataset
   - Physically: OL event shows `n` separate datasets (one per partition)
4. This can potentially bloat the OL event if number of partitions are huge (potentially >thousands)

**Cause:**
when a user tries to read a table, like done in below spark code:
```
df_read = spark.read.format("parquet") \
    .load(f"s3://{bucket}/path/to/data/{source_table}/id=*")
```
it gives us `n` inputs in the OL event
![image](https://github.com/user-attachments/assets/1b6b5655-0f08-4af9-8639-921ca89ece6e)

In this case we have n=3, but potentially it can be a large number in practice.

**Purpose:**
Combine all the individual partitioned inputs into a single input.
- This would make more sense for the end user interested in lineage info. 
- Lineage is captured at Data asset level and having an individual input object for each partition is redundant information for the end user.
- each input object which is a partition of a table would contain duplicate information.
- AWS Glue tables can have >10,000,000 partitions ([AWS Documentation](https://docs.aws.amazon.com/general/latest/gr/glue.html))
- Current approach would generate an equal number of input entries

**Proposed implementation**

1. **Dataset Representation**:
   - Replace multiple partition-level entries with one table-level entry
   - Apply this even when reading specific partitions (e.g., `id=1`)
```
e.g., s3://{bucket}/path/to/data/{source_table}/id=1 
```
the input dataset should show asset as source_table level instead of partition.

2. **Partition Metadata**:
   Add new facets to preserve partition information if required:
   ```json
   input[].facets: {
     "is_partitioned": boolean,
     "number_of_partitions": integer
   }
   ```

**Advantages:**
- Automatically reduces the size of OL event
- better lineage experience for the end user

**Comment by dolfinus** [comment]
2. The approach described in the issue doesn't save data about exact partitions being read/written, it just mentions if table is partitioned or not.
IMHO, the Apache Gravitino approach can be used instead:
https://gravitino.apache.org/docs/0.7.0-incubating/manage-relational-metadata-using-gravitino#create-a-table
https://gravitino.apache.org/docs/0.7.0-incubating/manage-table-partition-using-gravitino/#add-partition
```json
{
  input[].facets: {
    partitioning: {
      strategy: identity,
      fields: [
        {
          name: "country",
          type: "string",
        },
        {
          name: "event_date",
          type: "timestamp"
        }
      ],
      partitions: [
        {
          name: "country=xx/event_date=20240101",
          fieldValues: [
            {
              name: "country",
              value: "xx",
            },
            {
              name: "event_date",
              value: "20250101"
            }
          ]
        }
      ]
    }
  }
}
```

**Comment by dolfinus** [comment]
Related: #185

**Comment by mobuchowski** [comment]
> AWS Glue tables can have >10,000,000 partitions ([AWS Documentation](https://docs.aws.amazon.com/general/latest/gr/glue.html))

Is this limit something that can be actually found in the wild?

I think it's very important to establish whether we can emit information about every partition, whether for whole dataset, or just queried/written part, or it's foolish effort because the real metadata size can be extremely large?

**Comment by pawel-big-lebowski** [comment]
Some time ago I put some thoughts about partitioning into the docs -> https://docs.google.com/document/d/1w4_3hVY5-BTnehiOGFk1wVSTD550seLlDVlR7RliKt4/edit?usp=sharing

Before going with the proposal in the doc, we could limit amount of inputs for this scenario. Without paritiioning support, this should be a single dataset which I thought is the behaviour we have implemented.

**Comment by rahul-madaan** [comment]
@pawel-big-lebowski I took a look at the partitioning doc, while it makes good proposal on partition facet, it does not include details on combining input partitions to display only single dataset.
Can we please include this in the roadmap for OL?

**Comment by dolfinus** [comment]
> it does not include details on combining input partitions to display only single dataset.

Could you elaborate, please? If table have partitions [part=1, part=2, part=3], and Spark reads only [part=1, part=2], but exclude part=3, should OL event contain only information about [part=1, part=2]? If the entire table is read without filtering by partition columns at all, should OL event include all 3 partitions, or none of them?

**Comment by lukejhoffman** [comment]
@dolfinus, I think we have two separate issues here.

1. OL inputs array facet is sending over multiple inputs (1 for each partition read) for a single dataset. Ideally, this would only be one input regardless of the # of partitions.

2. OL doesn't support partition related metadata as a separate facet.

Issue 1 would take priority here as this can cause very large OL payloads if a dataset has 100s or more partitions. Also, according to @pawel-big-lebowski, this should already be default behavior and maybe is a bug (?):

> Without paritiioning support, this should be a single dataset which I thought is the behaviour we have implemented.

 As for issue 2, this would be a nice to have at some point in the future.

**Comment by lukejhoffman** [comment]
@dolfinus, I just ran a test with adding "basePath", and I am still seeing multiple inputs for the same {source_table} inside the OL event (OL version 1.24.2).

**Comment by dolfinus** [comment]
Well, this is expected. You've asked Spark to read multiple directories, so each one is a dataset, If you need to filter table content against partition column, use:
```python
df_read = spark.read.format("parquet") \
    .load(f"s3://{bucket}/path/to/data/{source_table}")
    .where("id=123")
```

**Comment by lukejhoffman** [comment]
Right, but the proposal here is about how OpenLineage should define the dataset. A partition is a subset of a particular dataset, so the proposal is asking that OpenLineage represent all inputs at the "basePath" and not at the individual partition level.

**Comment by lukejhoffman** [comment]
@dolfinus, @pawel-big-lebowski , any thoughts on this?

**Comment by dolfinus** [comment]
Does someone really uses pattern like `spark.read.parquet(".../some/path/with/partitions/*")` in production to create a DataFrame? Is optimising this case really worth it?

**Comment by d-m-h** [comment]
Yes, team's in my organisation do specify individual partitions, and then
union them. This is mostly out of their control as they use a library to
read this data and the library is what controls the reading. Additionally,
the union operation presents its own problem, specifically incredibly long
job names that repeat a specific spark operation per partition.

Op ma 6 jan. 2025 10:39 schreef Maxim Martynov ***@***.***>:

**Comment by rodrigokawatani** [comment]
Additionally, regarding the use-cases to use asterisks (*), we often use the wildcard to select all the hours of a specific day (e.g `s3://bucket/path/to/data/year=2025/month=01/day=07/*/*.parquet`). This approach is particularity useful when interacting with data coming from streaming platforms, such as Kafka + Kafka Connect (to s3) combo. 
The performance consideration above also applies to this strategy.

**Comment by dolfinus** [comment]
I also hope that Spark integration for OL could send events with just `basePath` (=table location in HDFS/S3), and make partitions list a separated facet. Currently users have to use `spark.openlineage.dataset.removePath.pattern` to drop a part of a file path containing partition column values, to get consistent datasets between different runs of the same job (Spark application). Otherwise reading latest partition of a table produces different dataset each time, and users are not able to build lineage graph containing all the runs accessing the same dataset because these datasets are not related at all.

I personally could implement this in our a custom OL events consumer, but this does not reduce the size of OL events emitted in the first place.

I see 2 solutions here:
* Handle all datasets matching the regexp `(/[^/=]+=[^/=]+)+` and to cut off matching part from file path to make a dataset name? Like `["s3a://bucket/some/path/a=1/b=2", "s3a://bucket/some/path/a=2/b=3"] -> "s3a://bucket/some/path"`.
* If user set `spark.read.option("basePath", "s3a://bucket/some/path")`, replace per-partition datasets with one `basePath` dataset But I'm not sure how `basePath` is represented in LogicalPlan or if it is even included here.

Also, should this logic of merging per-partition datasets into one be a part of only Spark integration or be a part of OL client? Do Flink and Airflow integrations currently produce the same `dataset=each discovered partition` too, or their implementation is significantly different from Spark?
